version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - pip install --upgrade awscli
      - dotnet restore TweetCacheApi/TweetCacheApi.csproj
      - dotnet restore TweetCacheApiTest/TweetCacheApiTest.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output TweetCacheApi/TweetCacheApi.csproj
      - dotnet publish -c release -o ./test_output TweetCacheApiTest/TweetCacheApiTest.csproj
      - dotnet vstest TweetCacheApiTest/test_output/TweetCacheApiTest.dll
artifacts:
  files:
    - TweetCacheApi/build_output/**/*
    - scripts/**/*
    - appspec.yml
